version: '3'
services:
  api:
    image: digitalgenius/alpine-scala-sbt
    hostname: api
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    expose:
      - "9001"
    ports:
      - "127.0.0.1:9001:9001"
    volumes:
      - ./:/usr/src/app
    working_dir: /usr/src/app
    command: sbt run

  redis:
    image: redis:3.2.8-alpine
    read_only: true
    volumes:
      - redis:/data
    user: redis
    ports:
      - "127.0.0.1:6379:6379"

volumes:
  redis: